FROM ubuntu:focal

RUN apt update && \
    apt install -y curl git unzip && \
    adduser --disabled-password asdf

USER asdf:asdf

RUN git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.8.1 && \
    echo '. $HOME/.asdf/asdf.sh' >> ~/.bashrc && \
    echo '. $HOME/.asdf/completions/asdf.bash' >> ~/.bashrc

COPY ./docker/asdf-output /usr/local/bin/

CMD [ "/usr/local/bin/asdf-output" ]
